name: tiktok
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity: ^2.0.2
  http:
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  google_sign_in: ^4.5.9

#  cloud_firestore: ^0.16.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/group.png
    - assets/nameapp.png
    - assets/icons-250.png
    - assets/group72.png
    - assets/icons-4.png
    - assets/icons-23.png
    - assets/icons-89.png
    - assets/icons-90.png
    - assets/icons-93.png
    - assets/icons-120.png
    - assets/icons8_crown.png
    - assets/icons-255.png
    - assets/NoPath - Copy (-4.png
    - assets/NoPath - Copy-4.png
    - assets/Union 27.png
    - assets/tym 3.png
    - assets/grapth.png
    - assets/push.png
    - assets/buttonNex.png
    - assets/icons-150.png
    - assets/icons-149.png
    - assets/icons-117.png
    - assets/icons-163.png
    - assets/icons-167.png
    - assets/icons-58.png
    - assets/icons-162.png
    - assets/icons-245.png
    - assets/icons-168.png
    - assets/icons-138.png
    - assets/icons8_confetti_3.png
    - assets/NoPath - Copy (23).png
    - assets/selfie-wall-posing-with-props.png
    - assets/NoPath - Copy (26).png
    - assets/NoPath - Copy (25).png
    - assets/NoPath - Copy (24).png
    - assets/Group 79.png
    - assets/NoPath - Copy (22).png
    - assets/NoPath - Copy (21).png
    - assets/NoPath - Copy (19).png
    - assets/NoPath - Copy (18).png
    - assets/NoPath - Copy (17).png
    - assets/NoPath - Copy (15).png
    - assets/LikeTym.png
    - assets/icons8_chat_bubble.png
    - assets/icons8_forward_arrow.png
    - assets/icons8_ratings.png
    - assets/Group 85.png
    - assets/Group 84.png
    - assets/Group 86.png
    - assets/Group 87.png
    - assets/Group 88.png
    - assets/Ellipse 22.png
    - assets/Group 39.png
    - assets/Group 54.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
